[package]
name = "ncrypt0r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic-crypt = "3.1.10"
anyhow = "1"
clap = { version = "4.0.7", features=["derive"] }